PPKProjekt/Pages/CRUDPutniNalog/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using PPKProjekt.Models;
using PPKProjekt.Repository;

namespace PPKProjekt.Pages.CRUDPutniNalog
{
    public class CreateModel : PageModel
    {
        private readonly IPutniNalogRepository repo;
        private readonly IVozacRepository vozacRepo;
        private readonly IVoziloRepository voziloRepo;
        

        public CreateModel()
        {
            repo = new PutniNalogRepository();
            vozacRepo = new VozacRepository();
            voziloRepo= new VoziloRepository();
            
        }

        public IActionResult OnGet()
        {
            Vozaci = vozacRepo.FindAll().Select(x => new SelectListItem
            {
                Value = x.IDVozac.ToString(),
                Text = $"{x.Ime} {x.Prezime}"
            }).ToList();
            Vozila = voziloRepo.FindAll().Select(x => new SelectListItem
            {
                Value = x.IDVozilo.ToString(),
                Text = $"{x.Tip} {x.Marka}"
            }).ToList();

            return Page();
        }



        [BindProperty]
        public PutniNalog PutniNalog { get; set; }



        [BindProperty]
        public int Vozilo { get; set; }
        [BindProperty]
        public int Vozac { get; set; }
        public List<SelectListItem> Vozaci { get; set; }
        public List<SelectListItem> Vozila { get; set; }

        public async Task<IActionResult> OnPostAsync()
        {
            PutniNalog.Vozilo = voziloRepo.FindById(Vozilo);
            PutniNalog.Vozac = vozacRepo.FindById(Vozac);
            if (!repo.FindBetweenDates(PutniNalog.StartDate,PutniNalog.StopDate).Any())
            {
                

                if (!ModelState.IsValid)
                {
                    return Page();
                }

            
                repo.Create(PutniNalog);

                return RedirectToPage("./Index");
            }
            else
            {
                return RedirectToPage("./VoziloZauzeto");

            }

        }
    }
}

PPKProjekt/Pages/CRUDPutniNalog/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PPKProjekt.Models;
using PPKProjekt.Repository;

namespace PPKProjekt.Pages.CRUDPutniNalog
{
    public class DeleteModel : PageModel
    {
        private readonly IPutniNalogRepository repo;

        public DeleteModel()
        {
            repo = new PutniNalogRepository();
        }

        [BindProperty]
        public PutniNalog PutniNalog { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            PutniNalog = repo.FindAll().FirstOrDefault(m => m.IDPutniNalog == id);
            /*await _context.Vozaci.FirstOrDefaultAsync(m => m.IDVozac == id);*/

            if (PutniNalog == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }



            if (PutniNalog != null)
            {
                repo.Delete(PutniNalog);
            }

            return RedirectToPage("./Index");
        }
    }
}

PPKProjekt/Pages/CRUDPutniNalog/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PPKProjekt.Models;
using PPKProjekt.Repository;

namespace PPKProjekt.Pages.CRUDPutniNalog
{
    public class DetailsModel : PageModel
    {
        private readonly IPutniNalogRepository repo;

        public DetailsModel()
        {
            repo = new PutniNalogRepository();
        }
        public PutniNalog PutniNalog { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            PutniNalog = repo.FindAll().FirstOrDefault(m => m.IDPutniNalog == id);

            if (PutniNalog == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

PPKProjekt/Pages/CRUDPutniNalog/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using PPKProjekt.Models;
using PPKProjekt.Repository;

namespace PPKProjekt.Pages.CRUDPutniNalog
{
    public class EditModel : PageModel
    {
        private readonly IPutniNalogRepository repo;
        private readonly IVozacRepository vozacRepo;
        private readonly IVoziloRepository voziloRepo;

        public EditModel()
        {
            repo = new PutniNalogRepository();
            vozacRepo = new VozacRepository();
            voziloRepo = new VoziloRepository();
        }
        [BindProperty]
        public PutniNalog PutniNalog { get; set; }
        [BindProperty]
        public int Vozilo { get; set; }
        [BindProperty]
        public int Vozac { get; set; }
        public List<SelectListItem> Vozaci { get; set; }
        public List<SelectListItem> Vozila { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            PutniNalog = repo.FindAll().FirstOrDefault(m => m.IDPutniNalog == id);
            Vozaci = vozacRepo.FindAll().Select(x => new SelectListItem
            {
                Value = x.IDVozac.ToString(),
                Text = $"{x.Ime} {x.Prezime}"
            }).ToList();
            Vozila = voziloRepo.FindAll().Select(x => new SelectListItem
            {
                Value = x.IDVozilo.ToString(),
                Text = $"{x.Tip} {x.Marka}"
            }).ToList();
            Vozac = PutniNalog.Vozac.IDVozac;
            Vozilo = PutniNalog.Vozilo.IDVozilo;
            if (PutniNalog == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            //_context.Attach(Vozac).State = EntityState.Modified;


            try
            {
                PutniNalog.Vozilo = voziloRepo.FindById(Vozilo);
                PutniNalog.Vozac = vozacRepo.FindById(Vozac);
                if (!repo.FindBetweenDates(PutniNalog.StartDate, PutniNalog.StopDate).Any(x=>x.IDPutniNalog!=PutniNalog.IDPutniNalog))
                {
                    repo.Update(PutniNalog);
                    return RedirectToPage("./Index");

                }
                else {
                    return RedirectToPage("./VoziloZauzeto");

                }
            }
            catch (SqlException)
            {
                if (!PutniNalogExists(PutniNalog.IDPutniNalog))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

        }

        private bool PutniNalogExists(int id)
        {
            return repo.FindAll().Any(e => e.IDPutniNalog == id);
        }

    }
}

PPKProjekt/Pages/CRUDPutniNalog/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using PPKProjekt.Models;
using PPKProjekt.Repository;

namespace PPKProjekt.Pages.CRUDPutniNalog
{
    public class IndexModel : PageModel
    {


        private readonly IPutniNalogRepository repo;
        public enum NalogState { Aktivni,Buduci,Zatvoreni }




        [BindProperty]
        public NalogState? SelectedState { get; set; }
        public IList<SelectListItem> SelectedStateList { get; set; } = new List<SelectListItem>();




        public IndexModel()
        {
            repo = new PutniNalogRepository();
        }
        public void OnPost()
        {
            repo.InsertTestCase();
            PutniNalog = repo.FindAll().ToList();


        }

        public IList<PutniNalog> PutniNalog { get; set; }

        public void OnGet(NalogState? nowState)
        {
            
            SelectedStateList.Add(new SelectListItem() { Text = "All", Value = "All" });
            SelectedStateList.Add(new SelectListItem() { Text = NalogState.Aktivni.ToString(), Value = NalogState.Aktivni.ToString() });
            SelectedStateList.Add(new SelectListItem() { Text = NalogState.Buduci.ToString(), Value = NalogState.Buduci.ToString() });
            SelectedStateList.Add(new SelectListItem() { Text = NalogState.Zatvoreni.ToString(), Value = NalogState.Zatvoreni.ToString() });
            if (nowState == NalogState.Aktivni)
            {
                PutniNalog = repo.FindBetweenDates(DateTime.Now.AddDays(-1), DateTime.Now).ToList();
            }
            else if (nowState == NalogState.Buduci)
            {
                PutniNalog = repo.FindBetweenDates(DateTime.Now.AddDays(1), System.Data.SqlTypes.SqlDateTime.MaxValue.Value).ToList();

            }
            else if (nowState == NalogState.Zatvoreni)
            {
                PutniNalog = repo.FindBetweenDates(System.Data.SqlTypes.SqlDateTime.MinValue.Value, DateTime.Now.AddDays(-1)).ToList();
            }
            else
            {
                PutniNalog = repo.FindAll().ToList();
            }
            SelectedState = nowState;

        }
        public IActionResult OnPostFilterGenerated()
        {
            return RedirectToPage("./Index", new { nowState=SelectedState });
        }

    }
}

PPKProjekt/Pages/CRUDPutniNalog/VoziloZauzeto.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PPKProjekt.Pages
{
    public class VoziloZauzetoModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

PPKProjekt/Pages/CRUDRute/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using PPKProjekt.Models;
using PPKProjekt.Repository;

namespace PPKProjekt.Pages.CRUDRute
{
    public class CreateModel : PageModel
    {
        private IRutaRepository rutarepo;
        private IPutniNalogRepository pnRepo;


        public CreateModel()
        {
            this.rutarepo = new RutaRepository();
            this.pnRepo = new PutniNalogRepository();
        }

        public IActionResult OnGet(int? id)
        {
            pnID = (int)id;
            return Page();
        }

        [BindProperty]
        public int pnID { get; set; }

        [BindProperty]
        public Ruta Ruta { get; set; }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            Ruta.PutniNalog = pnRepo.FindById(pnID);

            rutarepo.Create(Ruta);

            return RedirectToPage("../CRUDPutniNalog/Index");
        }
    }
}

PPKProjekt/Pages/CRUDRute/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using PPKProjekt.Models;
using PPKProjekt.Repository;

namespace PPKProjekt.Pages.CRUDRute
{
    public class DeleteModel : PageModel
    {
        private IRutaRepository rutarepo;

        public DeleteModel()
        {
            this.rutarepo = new RutaRepository();
        }

        [BindProperty]
        public Ruta Ruta { get; set; }

        public IActionResult OnGet(int? id, int? pnid)
        {
            if (id == null )
            {
                return NotFound();
            }

            Ruta = rutarepo.FindById((int)id);

            if (Ruta == null)
            {
                return NotFound();
            }
            return Page();
        }

        public IActionResult OnPost(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Ruta = rutarepo.FindById((int)id);
            if (Ruta != null)
            {
                rutarepo.Delete(Ruta);
            }

            return RedirectToPage("../CRUDPutniNalog/Index");
        }
    }
}

PPKProjekt/Pages/CRUDRute/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using PPKProjekt.Models;
using PPKProjekt.Repository;

namespace PPKProjekt.Pages.CRUDRute
{
    public class DetailsModel : PageModel
    {
        private IRutaRepository rutarepo;

        public DetailsModel()
        {
            this.rutarepo = new RutaRepository();
        }

        public Ruta Ruta { get; set; }

        public  IActionResult OnGet(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Ruta = rutarepo.FindById((int)id);

            if (Ruta == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

PPKProjekt/Pages/CRUDRute/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PPKProjekt.Models;
using PPKProjekt.Repository;

namespace PPKProjekt.Pages.CRUDRute
{
    public class EditModel : PageModel
    {
        private IRutaRepository rutarepo;
        private IPutniNalogRepository pnrepo;

        public EditModel()
        {
            this.rutarepo = new RutaRepository();
            this.pnrepo = new PutniNalogRepository();
        }
        [BindProperty]
        public Ruta Ruta { get; set; }

        public  IActionResult OnGet(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Ruta = rutarepo.FindById(((int)id));
            

            if (Ruta == null)
            {
                return NotFound();
            }
            return Page();
        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            int id = rutarepo.FindById(Ruta.IDRuta).PutniNalog.IDPutniNalog;
            Ruta.PutniNalog = pnrepo.FindById(id);
            try
            {
                rutarepo.Update(Ruta);
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!RutaExists(Ruta.IDRuta))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("../CRUDPutniNalog/Index");
        }

        private bool RutaExists(int id)
        {
            return rutarepo.FindById(id)!=null;
        }
    }
}

PPKProjekt/Pages/CRUDServis/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using PPKProjekt.Models;
using PPKProjekt.Repository;

namespace PPKProjekt.Pages.CRUDServis
{
    public class DeleteModel : PageModel
    {
        private IServisRepository servrepo;

        public DeleteModel()
        {
            servrepo = new ServisRepository();
        }


        [BindProperty]
        public Servis Servis { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Servis = servrepo.FindById((int)id);

            if (Servis == null)
            {
                return NotFound();
            }
            return Page();
        }

        public  IActionResult OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Servis = servrepo.FindById((int)id);

            if (Servis != null)
            {
                servrepo.Delete(Servis);
            }

            return RedirectToPage("./Index");
        }
    }
}

PPKProjekt/Pages/CRUDPutniNalog/Create.cshtml
@page
@model PPKProjekt.Pages.CRUDPutniNalog.CreateModel
@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>PutniNalog</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <select asp-for="Vozac" asp-items="Model.Vozaci"></select>

            </div>
            @*<label asp-for="PutniNalog.Vozac.Ime" class="control-label"></label>
        <input asp-for="PutniNalog.Vozac.Ime" class="form-control" />
        <span asp-validation-for="PutniNalog.Vozac.Ime" class="text-danger"></span>*@
            <div class="form-group">
                <select asp-for="Vozilo" asp-items="Model.Vozila"></select>

            </div>
            <div class="form-group">
                <label asp-for="PutniNalog.StartGrad" class="control-label"></label>
                <input asp-for="PutniNalog.StartGrad" class="form-control" />
                <span asp-validation-for="PutniNalog.StartGrad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PutniNalog.StopGrad" class="control-label"></label>
                <input asp-for="PutniNalog.StopGrad" class="form-control" />
                <span asp-validation-for="PutniNalog.StopGrad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PutniNalog.StartDate" class="control-label"></label>
                <input asp-for="PutniNalog.StartDate" class="form-control" />
                <span asp-validation-for="PutniNalog.StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PutniNalog.StopDate" class="control-label"></label>
                <input asp-for="PutniNalog.StopDate" class="form-control" />
                <span asp-validation-for="PutniNalog.StopDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PPKProjekt/Pages/CRUDPutniNalog/Delete.cshtml
@page
@model PPKProjekt.Pages.CRUDPutniNalog.DeleteModel
@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Putni Nalog</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PutniNalog.Vozac.Ime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PutniNalog.Vozac.Ime)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PutniNalog.Vozac.Prezime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PutniNalog.Vozac.Prezime)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PutniNalog.Vozilo.Tip)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PutniNalog.Vozilo.Tip)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PutniNalog.Vozilo.Marka)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PutniNalog.Vozilo.Marka)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PutniNalog.StartGrad)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PutniNalog.StartGrad)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PutniNalog.StopGrad)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PutniNalog.StopGrad)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PutniNalog.StartDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PutniNalog.StartDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PutniNalog.StopDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PutniNalog.StopDate)
        </dd>
    </dl>

    <form method="post">
        <input type="hidden" asp-for="PutniNalog.IDPutniNalog" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>


PPKProjekt/Pages/CRUDPutniNalog/Details.cshtml
@page
@model PPKProjekt.Pages.CRUDPutniNalog.DetailsModel
@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Putni Nalog</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PutniNalog.Vozac.Ime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PutniNalog.Vozac.Ime)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PutniNalog.Vozac.Prezime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PutniNalog.Vozac.Prezime)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PutniNalog.Vozilo.Tip)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PutniNalog.Vozilo.Tip)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PutniNalog.Vozilo.Marka)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PutniNalog.Vozilo.Marka)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PutniNalog.StartGrad)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PutniNalog.StartGrad)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PutniNalog.StopGrad)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PutniNalog.StopGrad)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PutniNalog.StartDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PutniNalog.StartDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PutniNalog.StopDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PutniNalog.StopDate)
        </dd>
    </dl>
</div>
<div>
    <a asp-page="./Edit" asp-route-id="@Model.PutniNalog.IDPutniNalog">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

PPKProjekt/Pages/CRUDPutniNalog/Index.cshtml
@page
@model PPKProjekt.Pages.CRUDPutniNalog.IndexModel
@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-page="Create">Create New</a>
</p>
<form class="" id="FilterForm" method="post" asp-page-handler="FilterGenerated">
    <label asp-for=" SelectedState"></label>
    <select class="form-control mb-1" asp-for="SelectedState"
            asp-items="@Model.SelectedStateList" onchange="this.form.submit()"></select>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PutniNalog[0].Vozac.Ime)
                @Html.DisplayNameFor(model => model.PutniNalog[0].Vozac.Prezime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PutniNalog[0].Vozilo.Tip)
                @Html.DisplayNameFor(model => model.PutniNalog[0].Vozilo.Marka)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PutniNalog[0].StartGrad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PutniNalog[0].StopGrad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PutniNalog[0].StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PutniNalog[0].StopDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @{if (Model != null)
            {
                foreach (var item in Model.PutniNalog)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Vozac.Ime)
                            @Html.DisplayFor(modelItem => item.Vozac.Prezime)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Vozilo.Tip)
                            @Html.DisplayFor(modelItem => item.Vozilo.Marka)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.StartGrad)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.StopGrad)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.StartDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.StopDate)
                        </td>
                        <td>
                            <a asp-page="./Edit" asp-route-id="@item.IDPutniNalog">Edit</a> |
                            <a asp-page="./Details" asp-route-id="@item.IDPutniNalog">Details</a> |
                            <a asp-page="./Delete" asp-route-id="@item.IDPutniNalog">Delete</a> |
                            <a asp-page="../CRUDRute/Index" asp-route-id="@item.IDPutniNalog">See Routes</a>

                        </td>
                    </tr>
                }
            } }
    </tbody>
</table>


<form method="post"><button class="btn btn-default">Insert Test Case</button></form>

PPKProjekt/Pages/CRUDPutniNalog/VoziloZauzeto.cshtml
@page
@model PPKProjekt.Pages.VoziloZauzetoModel
@{
    ViewData["Title"] = "VoziloZauzeto";
}

<h2>VoziloZauzeto</h2>
<p>U vremenu odabranom za putni nalog, odabrano vozilo je zauzeto</p>